application: sbugsbc
version: 1_6
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static
  expiration: "1d"

- url: /gallery/.*/gallery.swf
  static_files: static/gallery.swf
  upload: static/gallery.swf

- url: .*
  script: main.py

skip_files:
- ^(.*/)?\.git/?(.*)
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
